 version: '2'
 services:
   db:
     image: postgres:9.6
     environment:
      - POSTGRES_USER=voty
      - POSTGRES_PASSWORD=204rkmafd90-ad
     volumes:
       - ./data/db:/var/lib/postgresql/data
   web:
     build: .
     env:
      - VIRTUAL_HOST=abstimmen.bewegung.jetzt
      - DATABASE_URL=postgres://voty:204rkmafd90-ad@db/voty
     command: bash /code/etc/docker-start.sh
     volumes:
       - ./data/uploads:/code/static
     ports:
       - "8000:8000"
     depends_on:
       - db