 version: '2'
 services:
   db:
     image: postgres:9.6
     environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=voty
      - POSTGRES_PASSWORD=204rkmafd90-ad
     volumes:
       - ./data/db:/var/lib/postgresql/data
   web:
     build: .
     environment:
      - VIRTUAL_HOST=abstimmen.bewegung.jetzt
      - DATABASE_URL=postgres://voty:204rkmafd90-ad@db/voty
     command: gunicorn -w 3 -b 0.0.0.0 voty.wsgi
     volumes:
       - ./data/public:/code/public
     ports:
       - "8000:8000"
     links:
       - db